language: node_js

node_js: 
 - "10"
jdk:
 - oraclejdk8

addons:
  sonarcloud: true

script:
 # - npm run cover
 - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=camilocartagena-github -Dsonar.projectKey=camilocartagena_CalculatorNodeJS -Dsonar.sources='./app' -X